const ATTEMPT_KEY='htmlQuestAttempt',RESULT_KEY='htmlQuestResult',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const quests=[
 {name:'HTML TEMPLE',title:'Restore the HTML Temple',story:'Struktur utama temple hilang. Bangun kembali halaman HTML.',goal:'Susun struktur HTML agar halaman memiliki body dan heading utama.',mission:'Susun struktur HTML agar halaman memiliki body dan heading utama.',hint:'Heading utama diletakkan di dalam <body>.',req:['Gunakan elemen body','Letakkan heading h1 di dalam body'],answer:['body-open','h1-open','h1-content','h1-close','body-close'],blocks:[['body-open','<body>'],['body-close','</body>'],['h1-open','<h1>'],['h1-content','HTML Quest'],['h1-close','</h1>'],['h2-open','<h2>'],['p-open','<p>'],['p-close','</p>']],wrong:'Periksa urutan body dan heading utama. Heading harus berada di dalam body.'},
 {name:'LINK BRIDGE',title:'Reconnect the Link Bridge',story:'Jembatan kehilangan tautannya. Hubungkan kembali portal kampus.',goal:'Buat portal menuju website Telkom University.',mission:'Buat portal menuju website Telkom University.',hint:'Tujuan hyperlink ditentukan menggunakan atribut href.',req:['Gunakan anchor dengan href yang tepat','Letakkan teks portal di dalam anchor'],answer:['link-open','link-content','link-close'],blocks:[['link-open','<a href="https://telkomuniversity.ac.id">'],['link-content','Telkom University'],['link-close','</a>'],['link-src','<a src="https://telkomuniversity.ac.id">'],['link-tag','<link href="https://telkomuniversity.ac.id">'],['p-open','<p>']],wrong:'Periksa atribut yang menentukan tujuan hyperlink dan susunan tag anchor.'},
 {name:'TABLE DUNGEON',title:'Unlock the Table Dungeon',story:'Gerbang dungeon terkunci oleh tabel yang rusak.',goal:'Buat header tabel yang mencakup 3 kolom.',mission:'Buat header tabel yang mencakup 3 kolom.',hint:'colspan digunakan untuk menggabungkan beberapa kolom.',req:['Susun table dan baris tabel','Gunakan th dengan colspan 3'],answer:['table-open','tr-open','th-open','th-content','th-close','tr-close','table-close'],blocks:[['table-open','<table>'],['tr-open','<tr>'],['th-open','<th colspan="3">'],['th-content','Data Mahasiswa'],['th-close','</th>'],['tr-close','</tr>'],['table-close','</table>'],['td-open','<td colspan="3">'],['rowspan-open','<th rowspan="3">'],['div-open','<div>']],wrong:'Periksa elemen header tabel dan atribut yang membuatnya mencakup tiga kolom.'},
 {name:'IMAGE FOREST',title:'Restore the Image Forest',story:'Bug Lord mengganti atribut sumber gambar.',goal:'Pilih atribut yang menentukan alamat gambar.',mission:'Perbaiki atribut gambar agar sumbernya terbaca.',hint:'Alamat gambar ditentukan dengan atribut src.',req:['Pilih atribut sumber gambar yang tepat'],answer:['src'],blocks:[['src','src'],['href','href'],['action','action'],['method','method']],wrong:'Periksa kembali atribut yang digunakan untuk menentukan alamat gambar.',build(ids){return `<img ${ids[0]?this.blocks.find(b=>b[0]===ids[0])?.[1]:'_____'}="https://picsum.photos/300/180" alt="Magic Image">`}},
 {name:'FORM CASTLE',title:'Defeat the Bug Lord',story:'Bug Lord menjaga gerbang terakhir. Pulihkan formulir untuk mengalahkannya.',goal:'Susun form menuju /proses menggunakan POST dan input Nama Lengkap.',mission:'Susun form pengiriman data menuju /proses menggunakan POST dan input Nama Lengkap.',hint:'Perhatikan action, method POST, dan placeholder pada input.',req:['Form mengirim ke /proses dengan POST','Input memakai name nama dan placeholder Nama Lengkap'],answer:['form-open','input-name','form-close'],blocks:[['form-open','<form action="/proses" method="POST">'],['input-name','<input name="nama" placeholder="Nama Lengkap">'],['form-close','</form>'],['form-href','<form href="/proses">'],['form-get','<form action="/proses" method="GET">'],['input-href','<input href="nama">'],['input-email','<input name="nama" placeholder="Email">']],wrong:'Periksa action, method POST, dan placeholder input, lalu susun input di dalam form.'}
];
let state=null,timer=null,pending=false,selected=null,drag=null,suppressClick=false;
function save(){if(state)localStorage.setItem(ATTEMPT_KEY,JSON.stringify(state))}
function screen(id){$$('.screen').forEach(e=>e.classList.toggle('hidden',e.id!==id));if(state){state.screen=id;save()}scrollTo(0,0)}
function elapsed(){return state?Math.max(0,Math.floor(((state.finishedAt||Date.now())-state.startedAt)/1000)):0}
function clock(n){let h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function hudMarkup(){return `<span>PLAYER <b></b></span><span>HP <b class="hp-value">${'♥'.repeat(state.hp)}${'♡'.repeat(3-state.hp)}</b></span><span>XP <b>${String(state.xp).padStart(3,'0')}</b></span><span>TIME <b class="clock-value">${clock(elapsed())}</b></span>`}
function updateHud(){['mapHud','storyHud','battleHud'].forEach(id=>{let e=$('#'+id);e.innerHTML=hudMarkup();e.querySelector('span b').textContent=state.player.name});$$('.clock-value').forEach(e=>e.textContent=clock(elapsed()))}
function startTimer(){clearInterval(timer);timer=setInterval(()=>{if(state?.status==='active')$$('.clock-value').forEach(e=>e.textContent=clock(elapsed()))},1000)}
function map(){updateHud();$('#mapProgress').textContent=`REGION ${String(Math.min(state.level+1,5)).padStart(2,'0')} / 05`;$$('.map-node').forEach((n,i)=>{n.classList.toggle('active',i===state.level);n.classList.toggle('done',i<state.level);n.classList.toggle('locked',i>state.level);n.disabled=i!==state.level;n.setAttribute('aria-label',`${quests[i].name}, ${i<state.level?'selesai':i>state.level?'terkunci':'wilayah saat ini'}`)});let p=[['12%','28%'],['34%','60%'],['51%','28%'],['70%','62%'],['87%','29%']][Math.min(state.level,4)];$('#mapByte').style.left=p[0];$('#mapByte').style.top=p[1];screen('map')}
function story(){let q=quests[state.level];updateHud();$('#storyTag').textContent=state.level===4?'FINAL BOSS · LEVEL 05':`LEVEL ${String(state.level+1).padStart(2,'0')} · ${q.name}`;$('#storyTitle').textContent=q.title;$('#storyText').textContent=q.story;$('#goal').textContent=q.goal;$('#landmark').className='intro-landmark '+['temple','bridge','dungeon','forest','castle'][state.level];screen('story')}
function slots(){state.puzzles||={};let q=quests[state.level],s=state.puzzles[state.level],valid=new Set(q.blocks.map(b=>b[0]));if(!Array.isArray(s)||s.length!==q.answer.length)s=Array(q.answer.length).fill(null);state.puzzles[state.level]=s.map(id=>valid.has(id)?id:null);return state.puzzles[state.level]}
function info(id){return quests[state.level].blocks.find(b=>b[0]===id)}
function code(){let q=quests[state.level],s=slots();return q.build?q.build(s):s.map(id=>id?info(id)?.[1]:'').filter(Boolean).join('\n')}
function block(id,index=null){let b=document.createElement('button');b.type='button';b.className='code-block';b.dataset.blockId=id;if(index!==null)b.dataset.slotIndex=index;b.textContent=info(id)[1];b.setAttribute('aria-label',b.textContent+(index===null?', available':`, in slot ${index+1}`));b.addEventListener('click',blockClick);b.addEventListener('pointerdown',dragStart);return b}
function render(snap=null){let q=quests[state.level],s=slots(),used=new Set(s.filter(Boolean)),pool=$('#blockPool');pool.replaceChildren();q.blocks.filter(b=>!used.has(b[0])).forEach(b=>pool.append(block(b[0])));let area=$('#answerSlots');area.replaceChildren();s.forEach((id,i)=>{let el=document.createElement('div');el.className='drop-slot';el.dataset.slotIndex=i;el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label',`Answer slot ${i+1}, ${id?'filled':'empty'}`);let num=document.createElement('span');num.className='slot-number';num.textContent=i+1;let body=document.createElement('div');body.className='slot-content';if(id)body.append(block(id,i));else body.textContent='DROP HERE';el.append(num,body);el.addEventListener('click',slotClick);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();slotClick.call(el,e)}});if(i===snap)el.classList.add('snap');area.append(el)});$$('.code-block').forEach(e=>e.classList.toggle('selected',e.dataset.blockId===selected));$('#generatedCode').textContent=code()||'<!-- Susun blok HTML di atas -->';runCode();save()}
function blockClick(e){e.stopPropagation();if(suppressClick){suppressClick=false;return}let i=e.currentTarget.dataset.slotIndex;if(i!==undefined){slots()[+i]=null;selected=null;render();return}selected=selected===e.currentTarget.dataset.blockId?null:e.currentTarget.dataset.blockId;render()}
function slotClick(e){if(!selected||e.target.closest('.code-block'))return;place(selected,+this.dataset.slotIndex);selected=null}
function place(id,to,from=null){let s=slots(),old=s[to];if(from!==null)s[from]=null;s[to]=id;if(old&&from!==null)s[from]=old;render(to)}
function dragStart(e){if(e.button!==undefined&&e.button!==0)return;let src=e.currentTarget;drag={id:src.dataset.blockId,from:src.dataset.slotIndex===undefined?null:+src.dataset.slotIndex,x:e.clientX,y:e.clientY,src,active:false,pid:e.pointerId};src.setPointerCapture?.(e.pointerId);src.addEventListener('pointermove',dragMove);src.addEventListener('pointerup',dragEnd);src.addEventListener('pointercancel',dragEnd)}
function dragMove(e){if(!drag)return;if(!drag.active&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<7)return;e.preventDefault();if(!drag.active){drag.active=true;drag.src.classList.add('dragging');drag.ghost=drag.src.cloneNode(true);drag.ghost.className='code-block drag-ghost';document.body.append(drag.ghost)}drag.ghost.style.left=e.clientX+10+'px';drag.ghost.style.top=e.clientY+10+'px';$$('.drop-slot,.block-pool').forEach(x=>x.classList.remove('active'));document.elementFromPoint(e.clientX,e.clientY)?.closest('.drop-slot,.block-pool')?.classList.add('active')}
function dragEnd(e){let d=drag;if(!d)return;d.src.releasePointerCapture?.(d.pid);d.src.removeEventListener('pointermove',dragMove);d.src.removeEventListener('pointerup',dragEnd);d.src.removeEventListener('pointercancel',dragEnd);$$('.drop-slot,.block-pool').forEach(x=>x.classList.remove('active'));if(d.active){suppressClick=true;d.ghost?.remove();d.src.classList.remove('dragging');let target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.drop-slot,.block-pool');if(target?.classList.contains('drop-slot'))place(d.id,+target.dataset.slotIndex,d.from);else if(target?.classList.contains('block-pool')&&d.from!==null){slots()[d.from]=null;render()}}drag=null}
function requirements(q){let ul=$('#req');ul.replaceChildren();q.req.forEach(x=>{let li=document.createElement('li');li.textContent=x;ul.append(li)})}
function battle(){let q=quests[state.level];updateHud();selected=null;$('#battleTitle').textContent=q.name;$('#battleBadge').textContent=state.level===4?'FINAL BOSS':'CODE BATTLE';$('#arenaLabel').textContent=state.level===4?'FINAL BOSS':'BUG ENCOUNTER';$('#enemyName').textContent=state.level===4?'BUG LORD':'HTML BUG';$('.arena').classList.toggle('boss',state.level===4);$('#levelTag').textContent=`LEVEL ${String(state.level+1).padStart(2,'0')} · ${q.name}`;$('#missionTitle').textContent=q.title;$('#missionText').textContent=q.mission;requirements(q);$('#hint').disabled=false;$('#feedback').textContent=state.hints?.[state.level]?`BYTE: ${q.hint}`:'Susun blok HTML, lalu serang Bug!';$('#feedback').className='feedback';$('#monster').className='enemy';$('#enemyHealth').style.width='100%';render();screen('battle')}
function runCode(){$('#preview').srcdoc=code()}
function feedback(lines,good){let e=$('#feedback');e.textContent=lines.join('\n');e.className='feedback '+(good?'good':'bad')}
function valid(){let q=quests[state.level],s=slots();return q.answer.every((id,i)=>s[i]===id)}
function resultObject(status){return{...state.player,status,xp:state.xp,grade:Math.round(state.xp/5),time:clock(elapsed())}}
function addResult(dl,r){dl.replaceChildren();[['NAMA',r.name],['NIM',r.nim],['KELAS',r.kelas],['STATUS',r.status.toUpperCase()],['XP',`${r.xp}/500`],['NILAI',String(r.grade)],['COMPLETION TIME',r.time]].forEach(([a,b])=>{let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=a;dd.textContent=b;dl.append(dt,dd)})}
function finish(status){if(!state)return;state.status=status;state.finishedAt=Date.now();state.screen=status==='complete'?'result':'failed';save();clearInterval(timer);let r=resultObject(status);localStorage.setItem(RESULT_KEY,JSON.stringify(r));addResult($(status==='complete'?'#resultData':'#failedData'),r);screen(state.screen)}
function clearLevel(){state.xp+=100;$('#earned').textContent='+100 XP';$('#clearText').textContent=`${quests[state.level].name} berhasil dipulihkan!`;save();updateHud();$('#battleByte').classList.add('attack');$('#monster').classList.add('hit');$('#enemyHealth').style.width='0%';$$('.drop-slot').forEach(x=>x.classList.add('correct'));pending=true;setTimeout(()=>{pending=false;screen('clear')},560)}
$('#setup').addEventListener('submit',e=>{e.preventDefault();if(!$('#setup').reportValidity())return;state={player:{name:$('#name').value.trim(),nim:$('#nim').value.trim(),kelas:$('#kelas').value.trim()},startedAt:Date.now(),status:'active',screen:'map',level:0,hp:3,xp:0,puzzles:{},hints:{}};if(Object.values(state.player).some(v=>!v)){alert('Lengkapi Nama, NIM, dan Kelas.');return}save();startTimer();map()});
$$('.map-node').forEach(n=>n.addEventListener('click',()=>{if(state?.status==='active'&&+n.dataset.level===state.level)story()}));$('#enterBattle').addEventListener('click',battle);
$('#reset').addEventListener('click',()=>{state.puzzles[state.level]=Array(quests[state.level].answer.length).fill(null);selected=null;render();feedback(['Puzzle dikembalikan ke awal.'],true)});
$('#run').addEventListener('click',()=>{runCode();feedback(['Preview diperbarui dari susunan blok.'],true)});
$('#hint').addEventListener('click',()=>{if(!state)return;state.hints[state.level]=true;save();feedback([`BYTE: ${quests[state.level].hint}`,'Hint tidak mengurangi XP.'],true)});
$('#check').addEventListener('click',()=>{if(!state||pending)return;if(valid()){feedback(['✓ Semua konsep dan urutan sudah tepat.'],true);clearLevel();return}state.hp--;save();updateHud();$('#battleByte').classList.remove('hurt');void $('#battleByte').offsetWidth;$('#battleByte').classList.add('hurt');$('#answerSlots').classList.remove('wrong');void $('#answerSlots').offsetWidth;$('#answerSlots').classList.add('wrong');feedback([quests[state.level].wrong,`-1 HP · ${state.hp} HP tersisa. XP tidak berubah.`],false);if(state.hp<=0){pending=true;setTimeout(()=>{pending=false;finish('failed')},600)}});
$('#next').addEventListener('click',()=>{if(!state||state.status!=='active')return;state.level++;save();state.level>=quests.length?finish('complete'):map()});
$('#copy').addEventListener('click',async()=>{let r=JSON.parse(localStorage.getItem(RESULT_KEY)||'null');if(!r)return;let t=`HTML Quest — Code the World\nNama: ${r.name}\nNIM: ${r.nim}\nKelas: ${r.kelas}\nXP: ${r.xp}/500\nNilai: ${r.grade}\nCompletion Time: ${r.time}`;try{await navigator.clipboard.writeText(t);$('#copy').textContent='COPIED ✓'}catch{let a=document.createElement('textarea');a.value=t;$('#copy').after(a);a.select();if(document.execCommand('copy')){a.remove();$('#copy').textContent='COPIED ✓'}else{a.readOnly=true;a.className='copy-fallback';a.setAttribute('aria-label','Teks hasil untuk disalin manual');$('#copy').textContent='SELECT RESULT';a.focus();a.select()}}});
function resume(){let raw=localStorage.getItem(ATTEMPT_KEY);if(!raw)return;try{state=JSON.parse(raw);if(!state||!state.player||!Number.isInteger(state.level))throw Error('bad save');state.puzzles||={};state.hints||={};if(state.status!=='active'){let r=JSON.parse(localStorage.getItem(RESULT_KEY)||'null')||resultObject(state.status);addResult($('#lockedData'),r);screen('locked');return}startTimer();if(state.hp<=0){finish('failed');return}if(state.screen==='story')story();else if(state.screen==='battle')battle();else if(state.screen==='clear'){let q=quests[state.level];$('#clearText').textContent=`${q.name} berhasil dipulihkan!`;$('#earned').textContent='+100 XP';screen('clear')}else map()}catch(e){console.error('Saved attempt could not be read:',e);screen('locked')}}
resume();
