const ATTEMPT_KEY = 'htmlQuestAttempt';
const RESULT_KEY = 'htmlQuestResult';
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const quests = [
  {name:'HTML TEMPLE', title:'Restore the HTML Temple', story:'Struktur utama temple hilang. Bangun kembali halaman HTML.', goal:'Buat <body> dan sebuah <h1> di dalamnya.', mission:'Bangun struktur halaman yang menampilkan judul di dalam body.', code:'<!DOCTYPE html>\n<html>\n<head><title>HTML Quest</title></head>\n<!-- lengkapi di sini -->\n</html>', hint:'Konten halaman berada di dalam body. Letakkan heading utama di dalamnya.', checks:[['Tag <body> ditulis', (d,s)=>/<body(?:\s|>)/i.test(s.replace(/<!--[\s\S]*?-->/g,''))], ['<h1> berada di dalam body',d=>!!d.body.querySelector('h1')]]},
  {name:'LINK BRIDGE', title:'Reconnect the Link Bridge', story:'Jembatan kehilangan tautannya. Hubungkan kembali portal kampus.', goal:'Buat hyperlink menuju https://telkomuniversity.ac.id.', mission:'Buat tautan kampus yang bisa diklik.', code:'<h2>Portal Kampus</h2>\n<!-- buat hyperlink di sini -->', hint:'Gunakan elemen anchor. Tujuannya disimpan pada atribut href.', checks:[['Elemen <a> ditemukan',d=>!!d.querySelector('a')], ['href mengarah ke URL kampus',d=>[...d.querySelectorAll('a')].some(a=>a.getAttribute('href')==='https://telkomuniversity.ac.id')]]},
  {name:'TABLE DUNGEON', title:'Unlock the Table Dungeon', story:'Gerbang dungeon terkunci oleh tabel yang rusak.', goal:'Buat <th> dengan colspan="3" di dalam tabel.', mission:'Buat header tabel yang membentang tiga kolom.', code:'<table border="1">\n<tr><!-- header di sini --></tr>\n<tr><td>Nama</td><td>NIM</td><td>Kelas</td></tr>\n</table>', hint:'Header tabel memakai th. Atribut colspan menentukan jumlah kolom yang digabung.', checks:[['Header <th> ada dalam tabel',d=>!!d.querySelector('table th')], ['Header membentang 3 kolom',d=>[...d.querySelectorAll('table th')].some(th=>th.getAttribute('colspan')==='3')]]},
  {name:'IMAGE FOREST', title:'Restore the Image Forest', story:'Bug Lord mengganti atribut sumber gambar.', goal:'Perbaiki gambar dengan atribut src.', mission:'Perbaiki atribut gambar agar sumbernya terbaca.', code:'<h2>Magic Gallery</h2>\n<img href="https://picsum.photos/300/180" alt="Magic image">', hint:'Elemen img membaca alamat gambar dari src, bukan href.', checks:[['Elemen <img> ditemukan',d=>!!d.querySelector('img')], ['src berisi URL gambar yang benar',d=>[...d.querySelectorAll('img')].some(img=>img.getAttribute('src')==='https://picsum.photos/300/180')]]},
  {name:'FORM CASTLE', title:'Defeat the Bug Lord', story:'Bug Lord menjaga gerbang terakhir. Pulihkan formulir untuk mengalahkannya.', goal:'Buat form action="/proses" method="POST" dan input placeholder="Nama Lengkap".', mission:'Lengkapi tujuan form, metode pengiriman, dan petunjuk input.', code:'<form>\n<label>Nama:</label>\n<input type="text" name="nama">\n<button type="submit">Kirim</button>\n</form>', hint:'Form memerlukan action dan method. Teks petunjuk pada input memakai placeholder.', checks:[['Elemen <form> ditemukan',d=>!!d.querySelector('form')], ['action menuju /proses',d=>[...d.querySelectorAll('form')].some(f=>f.getAttribute('action')==='/proses')], ['method POST digunakan',d=>[...d.querySelectorAll('form')].some(f=>f.getAttribute('action')==='/proses'&&(f.getAttribute('method')||'').toLowerCase()==='post')], ['Input memiliki placeholder Nama Lengkap',d=>[...d.querySelectorAll('form')].some(f=>f.getAttribute('action')==='/proses'&&(f.getAttribute('method')||'').toLowerCase()==='post'&&[...f.querySelectorAll('input')].some(i=>i.getAttribute('placeholder')==='Nama Lengkap'))]]}
];
let state = null;
let timer = null;
let pending = false;
function screen(id){$$('.screen').forEach(el=>el.classList.toggle('hidden',el.id!==id));if(state){state.screen=id;save()}window.scrollTo(0,0)}
function save(){if(state)localStorage.setItem(ATTEMPT_KEY,JSON.stringify(state))}
function elapsed(){return state?Math.max(0,Math.floor(((state.finishedAt||Date.now())-state.startedAt)/1000)):0}
function clock(seconds){let h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return (h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function hudMarkup(){return `<span>PLAYER <b></b></span><span>HP <b class="hp-value">${'♥'.repeat(state.hp)}${'♡'.repeat(3-state.hp)}</b></span><span>XP <b>${String(state.xp).padStart(3,'0')}</b></span><span>TIME <b class="clock-value">${clock(elapsed())}</b></span>`}
function updateHud(){['mapHud','storyHud','battleHud'].forEach(id=>{let el=$('#'+id);el.innerHTML=hudMarkup();el.querySelector('span b').textContent=state.player.name});$$('.clock-value').forEach(el=>el.textContent=clock(elapsed()))}
function startTimer(){clearInterval(timer);timer=setInterval(()=>{if(state?.status==='active')$$('.clock-value').forEach(el=>el.textContent=clock(elapsed()))},1000)}
function map(){updateHud();$('#mapProgress').textContent=`REGION ${String(Math.min(state.level+1,5)).padStart(2,'0')} / 05`;$$('.map-node').forEach((node,i)=>{node.classList.toggle('active',i===state.level);node.classList.toggle('done',i<state.level);node.classList.toggle('locked',i>state.level);node.disabled=i!==state.level;node.setAttribute('aria-label',`${quests[i].name}, ${i<state.level?'selesai':i>state.level?'terkunci':'wilayah saat ini'}`)});let pos=[['12%','28%'],['34%','60%'],['51%','28%'],['70%','62%'],['87%','29%']][Math.min(state.level,4)];$('#mapByte').style.left=pos[0];$('#mapByte').style.top=pos[1];screen('map')}
function story(){let q=quests[state.level];updateHud();$('#storyTag').textContent=state.level===4?'FINAL BOSS · LEVEL 05':`LEVEL ${String(state.level+1).padStart(2,'0')} · ${q.name}`;$('#storyTitle').textContent=q.title;$('#storyText').textContent=q.story;$('#goal').textContent=q.goal;$('#landmark').className='intro-landmark '+['temple','bridge','dungeon','forest','castle'][state.level];screen('story')}
function requirements(q){let ul=$('#req');ul.replaceChildren();q.checks.forEach(([label])=>{let li=document.createElement('li');li.textContent=label;ul.append(li)})}
function battle(){let q=quests[state.level];updateHud();$('#battleTitle').textContent=q.name;$('#battleBadge').textContent=state.level===4?'FINAL BOSS':'CODE BATTLE';$('#arenaLabel').textContent=state.level===4?'FINAL BOSS':'BUG ENCOUNTER';$('#enemyName').textContent=state.level===4?'BUG LORD':'HTML BUG';$('.arena').classList.toggle('boss',state.level===4);$('#levelTag').textContent=`LEVEL ${String(state.level+1).padStart(2,'0')} · ${q.name}`;$('#missionTitle').textContent=q.title;$('#missionText').textContent=q.mission;requirements(q);$('#code').value=state.codes[state.level]??q.code;$('#hint').disabled=!!state.hints[state.level];$('#feedback').textContent=state.hints[state.level]?'Hint sudah digunakan. Maksimum level ini 75 XP.':'Tulis kode, lalu serang Bug!';$('#feedback').className='feedback';$('#monster').className='enemy';$('#enemyHealth').style.width='100%';runCode();screen('battle')}
function runCode(){// A sandbox without permissions blocks scripts and form navigation from student HTML.
  $('#preview').srcdoc=$('#code').value;
}
function feedback(lines,good){let el=$('#feedback');el.textContent=lines.join('\n');el.className='feedback '+(good?'good':'bad')}
function validate(){let source=$('#code').value;let doc=new DOMParser().parseFromString(source,'text/html');return quests[state.level].checks.map(([label,fn])=>({label,pass:!!fn(doc,source)}))}
function resultObject(status){return {...state.player,status,xp:state.xp,grade:Math.round(state.xp/5),time:clock(elapsed())}}
function addResult(dl,result){dl.replaceChildren();[['NAMA',result.name],['NIM',result.nim],['KELAS',result.kelas],['STATUS',result.status.toUpperCase()],['XP',`${result.xp}/500`],['NILAI',String(result.grade)],['COMPLETION TIME',result.time]].forEach(([label,value])=>{let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;dl.append(dt,dd)})}
function finish(status){if(!state)return;state.status=status;state.finishedAt=Date.now();state.screen=status==='complete'?'result':'failed';save();clearInterval(timer);let result=resultObject(status);localStorage.setItem(RESULT_KEY,JSON.stringify(result));addResult($(status==='complete'?'#resultData':'#failedData'),result);screen(state.screen)}
function showClear(){let gain=state.hints[state.level]?75:100;state.xp+=gain;state.codes[state.level]=$('#code').value;$('#earned').textContent=`+${gain} XP`;$('#clearText').textContent=`${quests[state.level].name} berhasil dipulihkan!`;state.screen='clear';save();updateHud();$('#battleByte').classList.add('attack');$('#monster').classList.add('hit');$('#enemyHealth').style.width='0%';pending=true;setTimeout(()=>{pending=false;screen('clear')},560)}
$('#setup').addEventListener('submit',event=>{event.preventDefault();if(!$('#setup').reportValidity())return;state={player:{name:$('#name').value.trim(),nim:$('#nim').value.trim(),kelas:$('#kelas').value.trim()},startedAt:Date.now(),status:'active',screen:'map',level:0,hp:3,xp:0,codes:{},hints:{}};if(Object.values(state.player).some(v=>!v)){alert('Lengkapi Nama, NIM, dan Kelas.');return}save();startTimer();map()});
$$('.map-node').forEach(node=>node.addEventListener('click',()=>{if(state?.status!=='active'||Number(node.dataset.level)!==state.level)return;story()}));
$('#enterBattle').addEventListener('click',battle);
$('#code').addEventListener('input',()=>{if(!state)return;state.codes[state.level]=$('#code').value;save()});
$('#run').addEventListener('click',()=>{runCode();feedback(['Preview diperbarui.'],true)});
$('#hint').addEventListener('click',()=>{if(!state||state.hints[state.level])return;state.hints[state.level]=true;save();$('#hint').disabled=true;feedback([`BYTE: ${quests[state.level].hint}`,'Maksimum XP level ini menjadi 75.'],true)});
$('#check').addEventListener('click',()=>{if(!state||pending)return;let checks=validate();if(checks.every(c=>c.pass)){feedback(checks.map(c=>'✓ '+c.label),true);showClear();return}state.hp--;save();updateHud();$('#battleByte').classList.remove('hurt');void $('#battleByte').offsetWidth;$('#battleByte').classList.add('hurt');feedback([...checks.map(c=>(c.pass?'✓ ':'✗ ')+c.label),`-1 HP · ${state.hp} HP tersisa.`],false);if(state.hp<=0){pending=true;setTimeout(()=>{pending=false;finish('failed')},600)}});
$('#next').addEventListener('click',()=>{if(!state||state.status!=='active')return;state.level++;save();if(state.level>=quests.length)finish('complete');else map()});
$('#copy').addEventListener('click',async()=>{let r=JSON.parse(localStorage.getItem(RESULT_KEY)||'null');if(!r)return;let text=`HTML Quest — Code the World\nNama: ${r.name}\nNIM: ${r.nim}\nKelas: ${r.kelas}\nXP: ${r.xp}/500\nNilai: ${r.grade}\nCompletion Time: ${r.time}`;try{await navigator.clipboard.writeText(text);$('#copy').textContent='COPIED ✓'}catch{let area=document.createElement('textarea');area.value=text;$('#copy').after(area);area.select();let ok=document.execCommand('copy');if(ok){area.remove();$('#copy').textContent='COPIED ✓'}else{area.readOnly=true;area.className='copy-fallback';area.setAttribute('aria-label','Teks hasil untuk disalin manual');$('#copy').textContent='SELECT RESULT';area.focus();area.select()}}});
function resume(){let raw=localStorage.getItem(ATTEMPT_KEY);if(!raw)return;try{state=JSON.parse(raw);if(!state||!state.player||!Number.isInteger(state.level))throw Error('bad save');if(state.status!=='active'){let r=JSON.parse(localStorage.getItem(RESULT_KEY)||'null')||resultObject(state.status);addResult($('#lockedData'),r);screen('locked');return}startTimer();if(state.hp<=0){finish('failed');return}if(state.screen==='story')story();else if(state.screen==='battle')battle();else if(state.screen==='clear'){let q=quests[state.level];$('#clearText').textContent=`${q.name} berhasil dipulihkan!`;$('#earned').textContent=`+${state.hints[state.level]?75:100} XP`;screen('clear')}else map()}catch(error){console.error('Saved attempt could not be read:',error);screen('locked')}}
resume();
